version: 2
  jobs:
    build:
      - run:
          name: install
          command: sudo pip install awscli
    steps:
      - deploy:
              prod:
                 branch: master
                 commands:
                         - aws s3 sync /home/ubuntu/S3ContinuousDeploy s3://aws-continue-deploy-lab --delete      
