version: 2
jobs:
  build:
    - run:
        name: install
        command: 'sudo pip install awscli'
  deploy:
    steps:
      - run:
          name: Deploy to S3
          command: aws s3 sync /home/ubuntu/S3ContinuousDeploy s3://aws-continue-deploy-lab --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
